### ISSUE TITLE
Alternatief voor Div

### ISSUE THREAD

**Issue by SanHont** [Khdulkadir/fix-the-flow-interactive-website#10]
Voor de semantiek is het misschien goed om te kijken naar een alternatief voor ene div, een div zelf is niet heel veel zeggend.

**Comment by Khdulkadir** [comment]
Veranderd naar article
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/aee561f3c4a63944b87f488ea144c393db51b45e/index.html#L149-L155
