### ISSUE TITLE
feedback op HiFi

### ISSUE THREAD

**Issue by Tolga1999** [Khdulkadir/fix-the-flow-interactive-website#3]
- Je zou de logo in je sidebar kunnen zetten, zie je vaak in designs op dribble of pinterest. Dit maakt het meer consistent en duidelijk. 
- Probeer consistentie te houden met je headings, H1s kan wat groter, ik zou voor de styling van de headings het consistent houden. Je kan voor je h2 ook gewoon gebruik maken van een rode background met witte tekst. 
- Binnen de leden pagina zou  je de volledige container van een lid klikbaar kunnen maken om naar de detailpage te kunnen gaan, verder zou je gebruik kunnen maken van de css property `cursor` om dit duidelijker te maken.

**Comment by Tolga1999** [comment]
Voor inspiratie zou je kunnen kijken naar dribble of pinterest

https://dribbble.com/following
https://nl.pinterest.com/

**Comment by Khdulkadir** [comment]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/28c08588e00aea270bd34d5db9fa09fdfde339f7/index.html#L20-L22
