### ISSUE TITLE
Gebruik maken van duidelijke class namen

### ISSUE THREAD

**Issue by Tolga1999** [Khdulkadir/fix-the-flow-interactive-website#4]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/7a7b7cd152d5e119c602dd9faea523935ce6fc36/index.html#L146-L148

om het duidelijker te kunnen maken zou je de volgende volgorde kunnen gebruiken voor de container nesting css names, `accounts-container` -> `accounts-lijstje` -> `account`

**Comment by Khdulkadir** [comment]
Gefixt
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/aee561f3c4a63944b87f488ea144c393db51b45e/index.html#L144-L164
