### ISSUE TITLE
probeer je code te formateren

### ISSUE THREAD

**Issue by Tolga1999** [Khdulkadir/fix-the-flow-interactive-website#5]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/7a7b7cd152d5e119c602dd9faea523935ce6fc36/index.html#L149-L160

je code is makkelijker te lezen als je het formateert, je zou hiervoor prettier kunnen gebruiken  (Vscode extension)

**Comment by Khdulkadir** [comment]
Gefixt
