### ISSUE TITLE
probeer meer gebruik te maken van semantische elementen 

### ISSUE THREAD

**Issue by Tolga1999** [Khdulkadir/fix-the-flow-interactive-website#6]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/7a7b7cd152d5e119c602dd9faea523935ce6fc36/index.html#L177

https://css-tricks.com/how-to-section-your-html/

**Comment by Tolga1999** [comment]
gebruik hier article, je gebruiikt voornamelijk tekst in een container

**Comment by Khdulkadir** [comment]
Veranderd naar article
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/aee561f3c4a63944b87f488ea144c393db51b45e/index.html#L149-L155
