### ISSUE TITLE
zet de content van je pagina in een main

### ISSUE THREAD

**Issue by Tolga1999** [Khdulkadir/fix-the-flow-interactive-website#7]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/7a7b7cd152d5e119c602dd9faea523935ce6fc36/index.html#L134

als je main gebruikt voor je content kan je makkelijker onderscheid maken tussen je header, main en footer

**Comment by Khdulkadir** [comment]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/28c08588e00aea270bd34d5db9fa09fdfde339f7/index.html#L139-L140
