### ISSUE TITLE
Account benaming

### ISSUE THREAD

**Issue by SanHont** [Khdulkadir/fix-the-flow-interactive-website#9]
Misschien is het makkelijker voor jezelf om inplaats van account1 tm account5 maar 1 class name te gebruiken aangezien ze toch wel het zelfde zijn. Dat maakt het net wat overzichtelijker.

**Comment by Khdulkadir** [comment]
https://github.com/Khdulkadir/fix-the-flow-interactive-website/blob/28c08588e00aea270bd34d5db9fa09fdfde339f7/index.html#L148
